import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import ClientSideRouter from "@/components/layouts/ClientSideRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ClientSideRouter>
          {children}
        </ClientSideRouter>
      </body>
    </html>
  );
}
